### ISSUE TITLE
USER STORY Username/Password

### ISSUE THREAD

**Issue by LeVlad** [LeVlad/loverunning#3]
In order to **log in securely** as a **member**, I can **set up a username and password**

## Acceptance Criteria ##

* Acceptance criteria 1 : Create Login options 

* Acceptance criteria 2 :  Ensure details are kept safe and encrypted

* Acceptance criteria 3 : Create " forgot password " option

## Tasks ##

- [ ] Create username and password form
- [ ] Ensure data is encrypted and saved safely
- [ ] Create "Forgot Password" option
- [ ] Create " Forgot Username" option
- [ ] Create Human recognition check ( CAPCHA, image choices,etc)
