### ISSUE TITLE
USER STORY <TITLE>

### ISSUE THREAD

**Issue by LeVlad** [LeVlad/loverunning#4]
In order to **vote on new race locations** as a **user**, I can **vote on the poll**

## Acceptance Criteria ##

* Acceptance criteria 1 : Option to vote exists

* Acceptance criteria 2 : Human verification check

* Acceptance criteria 3 : Submit button

## Tasks ##

- [ ] Create Submit button
- [ ] Implement CAPCHA or Image confirmation checks
- [ ] Create "Vote" clickable option
- [ ] Create confirmation alert
